name: Node CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Stop old process
        run: taskkill /F /IM node.exe
        continue-on-error: true

      - name: Start app with PM2
        shell: cmd
        run: pm2 restart index.js || pm2 start index.js