name: Node CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # your PC runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Stop old server (Windows safe)
        run: taskkill /F /IM node.exe || exit 0

      - name: Start Node app
        run: start /B npm start